# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PTree_cpp <- function(R, Y, X, Z, H, portfolio_weight, loss_weight, stocks, months, unique_months, first_split_var, second_split_var, num_stocks, num_months, min_leaf_size = 100L, max_depth = 5L, num_iter = 30L, num_cutpoints = 4L, eta = 1.0, equal_weight = FALSE, no_H = FALSE, abs_normalize = FALSE, weighted_loss = FALSE, lambda_mean = 0, lambda_cov = 0, lambda_mean_factor = 0, lambda_cov_factor = 0, early_stop = FALSE, stop_threshold = 0.95, lambda_ridge = 0, a1 = 0.05, a2 = 1.0, list_K, random_split = FALSE) {
    .Call(`_PTree_PTree_cpp`, R, Y, X, Z, H, portfolio_weight, loss_weight, stocks, months, unique_months, first_split_var, second_split_var, num_stocks, num_months, min_leaf_size, max_depth, num_iter, num_cutpoints, eta, equal_weight, no_H, abs_normalize, weighted_loss, lambda_mean, lambda_cov, lambda_mean_factor, lambda_cov_factor, early_stop, stop_threshold, lambda_ridge, a1, a2, list_K, random_split)
}

predict_PTree_cpp <- function(X, json_string, months) {
    .Call(`_PTree_predict_PTree_cpp`, X, json_string, months)
}

